// const swaggerAutogen = require('swagger-autogen');
// const endpointsFiles = ['./routes/admin.routes.ts', './routes/admission.routes.ts', './routes/category.routes.ts', './routes/certificate.routes.ts', './routes/contact.routes.ts', './routes/corporate.routes.ts', './routes/course.routes.ts', './routes/enquiry.routes.ts',
//     './routes/hackathon.routes.ts', './routes/instructor.routes.ts', './routes/message.routes.ts', './routes/newsletter.routes.ts', './routes/notice.routes.ts', './routes/partner.routes.ts', './routes/review.routes.ts', './routes/service.routes.ts',
//     './routes/skill.routes.ts', './routes/student.routes.ts', './routes/syllabus.routes.ts', './routes/training.routes.ts']

const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Parents: {
            father: "Simon Doe",
            mother: "Marie Doe"
        },
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                $ref: '#/category/'
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./index.ts']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.ts')           // Your project's root file
})